export default {
  wrapper: "daypicker",
  header: "daypicker__header",
  select: "daypicker__select",
  monthSelect: "daypicker__month-select",
  yearSelect: "daypicker__month-select",
  table: "daypicker__calendar",
  tableRow: "daypicker__calendar-row",
  tableCell: "daypicker__calendar-cell",
  tableHeaderRow: "daypicker__calendar-header-row",
  tableHeaderCell: "daypicker__calendar-header-cell",
  dayButton: "daypicker__day-button",
  isToday: "isToday",
  isSelected: "isSelected",
  srOnly: "sr-only",
};
